"""
This file was auto-generated by the script api.local.admin_tasks.general_admin.generate_table_classes_for_sql_queries.py
Rerun that file if you want recent changes in database models to be reflected here.
"""

class BaseTable:
    def __init__(self):
        self.table = f'projects_{self.__class__.__name__.lower()}'
        self.id = f'{self.table}.id'
        self.created = f'{self.table}.created'
        self.modified = f'{self.table}.modified'


class EntityUpdate(BaseTable):
    def __init__(self):
        super().__init__()
        self.entity_name = f'{self.table}.entity_name'
        self.entity_id = f'{self.table}.entity_id'
        self.json_patch = f'{self.table}.json_patch'
        self.json_reverse_patch = f'{self.table}.json_reverse_patch'
        
                
class ExternalSystem(BaseTable):
    def __init__(self):
        super().__init__()
        self.name = f'{self.table}.name'
        self.short_name = f'{self.table}.short_name'
        self.external_user_id_type = f'{self.table}.external_user_id_type'
        
                
class Project(BaseTable):
    def __init__(self):
        super().__init__()
        self.name = f'{self.table}.name'
        self.short_name = f'{self.table}.short_name'
        self.visibility = f'{self.table}.visibility'
        self.website_highlight = f'{self.table}.website_highlight'
        self.testing_group_id = f'{self.table}.testing_group_id'
        self.status = f'{self.table}.status'
        
                
class ProjectGroupVisibility(BaseTable):
    def __init__(self):
        super().__init__()
        self.project_id = f'{self.table}.project_id'
        self.user_group_id = f'{self.table}.user_group_id'
        
                
class ProjectTask(BaseTable):
    def __init__(self):
        super().__init__()
        self.project_id = f'{self.table}.project_id'
        self.task_type_id = f'{self.table}.task_type_id'
        self.description = f'{self.table}.description'
        self.earliest_start_date = f'{self.table}.earliest_start_date'
        self.closing_date = f'{self.table}.closing_date'
        self.signup_status = f'{self.table}.signup_status'
        self.visibility = f'{self.table}.visibility'
        self.website_highlight = f'{self.table}.website_highlight'
        self.testing_group_id = f'{self.table}.testing_group_id'
        self.external_system_id = f'{self.table}.external_system_id'
        self.external_task_id = f'{self.table}.external_task_id'
        self.base_url = f'{self.table}.base_url'
        self.status = f'{self.table}.status'
        self.progress_info = f'{self.table}.progress_info'
        self.progress_info_modified = f'{self.table}.progress_info_modified'
        
                
class ProjectTaskGroupVisibility(BaseTable):
    def __init__(self):
        super().__init__()
        self.project_task_id = f'{self.table}.project_task_id'
        self.user_group_id = f'{self.table}.user_group_id'
        
                
class TaskType(BaseTable):
    def __init__(self):
        super().__init__()
        self.name = f'{self.table}.name'
        self.short_name = f'{self.table}.short_name'
        
                
class User(BaseTable):
    def __init__(self):
        super().__init__()
        self.email = f'{self.table}.email'
        self.email_address_verified = f'{self.table}.email_address_verified'
        self.email_verification_token = f'{self.table}.email_verification_token'
        self.email_verification_expiry = f'{self.table}.email_verification_expiry'
        self.title = f'{self.table}.title'
        self.first_name = f'{self.table}.first_name'
        self.last_name = f'{self.table}.last_name'
        self.country_code = f'{self.table}.country_code'
        self.auth0_id = f'{self.table}.auth0_id'
        self.crm_id = f'{self.table}.crm_id'
        self.status = f'{self.table}.status'
        
                
class UserExternalAccount(BaseTable):
    def __init__(self):
        super().__init__()
        self.external_system_id = f'{self.table}.external_system_id'
        self.user_id = f'{self.table}.user_id'
        self.external_user_id = f'{self.table}.external_user_id'
        self.status = f'{self.table}.status'
        
                
class UserGroup(BaseTable):
    def __init__(self):
        super().__init__()
        self.name = f'{self.table}.name'
        self.short_name = f'{self.table}.short_name'
        self.url_code = f'{self.table}.url_code'
        
                
class UserGroupMembership(BaseTable):
    def __init__(self):
        super().__init__()
        self.user_id = f'{self.table}.user_id'
        self.user_group_id = f'{self.table}.user_group_id'
        
                
class UserProject(BaseTable):
    def __init__(self):
        super().__init__()
        self.user_id = f'{self.table}.user_id'
        self.project_id = f'{self.table}.project_id'
        self.status = f'{self.table}.status'
        self.ext_user_project_id = f'{self.table}.ext_user_project_id'
        
                
class UserTask(BaseTable):
    def __init__(self):
        super().__init__()
        self.user_project_id = f'{self.table}.user_project_id'
        self.project_task_id = f'{self.table}.project_task_id'
        self.status = f'{self.table}.status'
        self.consented = f'{self.table}.consented'
        self.progress_info = f'{self.table}.progress_info'
        self.ext_user_task_id = f'{self.table}.ext_user_task_id'
        
                