"""
This file was auto-generated by the script api.local.admin_tasks.general_admin.generate_table_classes_for_sql_queries.py
Rerun that file if you want recent changes in database models to be reflected here.
"""


class BaseTable:
    def __init__(self):
        self.table = f'projects_{self.__class__.__name__.lower()}'
        self.id = (f'{self.table}.id', f'{self.table}.id as {self.table[9:]}_id')
        self.created = (f'{self.table}.created', f'{self.table}.created as {self.table[9:]}_created')
        self.modified = (f'{self.table}.modified', f'{self.table}.modified as {self.table[9:]}_modified')


class EntityUpdate(BaseTable):
    def __init__(self):
        super().__init__()
        self.entity_name = (f'{self.table}.entity_name', f'{self.table}.entity_name as {self.table[9:]}_entity_name')
        self.entity_id = (f'{self.table}.entity_id', f'{self.table}.entity_id as {self.table[9:]}_entity_id')
        self.json_patch = (f'{self.table}.json_patch', f'{self.table}.json_patch as {self.table[9:]}_json_patch')
        self.json_reverse_patch = (f'{self.table}.json_reverse_patch', f'{self.table}.json_reverse_patch as {self.table[9:]}_json_reverse_patch')
        
                
class ExternalSystem(BaseTable):
    def __init__(self):
        super().__init__()
        self.name = (f'{self.table}.name', f'{self.table}.name as {self.table[9:]}_name')
        self.short_name = (f'{self.table}.short_name', f'{self.table}.short_name as {self.table[9:]}_short_name')
        self.external_user_id_type = (f'{self.table}.external_user_id_type', f'{self.table}.external_user_id_type as {self.table[9:]}_external_user_id_type')
        
                
class Project(BaseTable):
    def __init__(self):
        super().__init__()
        self.name = (f'{self.table}.name', f'{self.table}.name as {self.table[9:]}_name')
        self.short_name = (f'{self.table}.short_name', f'{self.table}.short_name as {self.table[9:]}_short_name')
        self.visibility = (f'{self.table}.visibility', f'{self.table}.visibility as {self.table[9:]}_visibility')
        self.website_highlight = (f'{self.table}.website_highlight', f'{self.table}.website_highlight as {self.table[9:]}_website_highlight')
        self.testing_group_id = (f'{self.table}.testing_group_id', f'{self.table}.testing_group_id as {self.table[9:]}_testing_group_id')
        self.status = (f'{self.table}.status', f'{self.table}.status as {self.table[9:]}_status')
        
                
class ProjectGroupVisibility(BaseTable):
    def __init__(self):
        super().__init__()
        self.project_id = (f'{self.table}.project_id', f'{self.table}.project_id as {self.table[9:]}_project_id')
        self.user_group_id = (f'{self.table}.user_group_id', f'{self.table}.user_group_id as {self.table[9:]}_user_group_id')
        
                
class ProjectTask(BaseTable):
    def __init__(self):
        super().__init__()
        self.project_id = (f'{self.table}.project_id', f'{self.table}.project_id as {self.table[9:]}_project_id')
        self.task_type_id = (f'{self.table}.task_type_id', f'{self.table}.task_type_id as {self.table[9:]}_task_type_id')
        self.description = (f'{self.table}.description', f'{self.table}.description as {self.table[9:]}_description')
        self.earliest_start_date = (f'{self.table}.earliest_start_date', f'{self.table}.earliest_start_date as {self.table[9:]}_earliest_start_date')
        self.closing_date = (f'{self.table}.closing_date', f'{self.table}.closing_date as {self.table[9:]}_closing_date')
        self.signup_status = (f'{self.table}.signup_status', f'{self.table}.signup_status as {self.table[9:]}_signup_status')
        self.visibility = (f'{self.table}.visibility', f'{self.table}.visibility as {self.table[9:]}_visibility')
        self.website_highlight = (f'{self.table}.website_highlight', f'{self.table}.website_highlight as {self.table[9:]}_website_highlight')
        self.testing_group_id = (f'{self.table}.testing_group_id', f'{self.table}.testing_group_id as {self.table[9:]}_testing_group_id')
        self.external_system_id = (f'{self.table}.external_system_id', f'{self.table}.external_system_id as {self.table[9:]}_external_system_id')
        self.external_task_id = (f'{self.table}.external_task_id', f'{self.table}.external_task_id as {self.table[9:]}_external_task_id')
        self.base_url = (f'{self.table}.base_url', f'{self.table}.base_url as {self.table[9:]}_base_url')
        self.status = (f'{self.table}.status', f'{self.table}.status as {self.table[9:]}_status')
        self.progress_info = (f'{self.table}.progress_info', f'{self.table}.progress_info as {self.table[9:]}_progress_info')
        self.progress_info_modified = (f'{self.table}.progress_info_modified', f'{self.table}.progress_info_modified as {self.table[9:]}_progress_info_modified')
        
                
class ProjectTaskGroupVisibility(BaseTable):
    def __init__(self):
        super().__init__()
        self.project_task_id = (f'{self.table}.project_task_id', f'{self.table}.project_task_id as {self.table[9:]}_project_task_id')
        self.user_group_id = (f'{self.table}.user_group_id', f'{self.table}.user_group_id as {self.table[9:]}_user_group_id')
        
                
class TaskType(BaseTable):
    def __init__(self):
        super().__init__()
        self.name = (f'{self.table}.name', f'{self.table}.name as {self.table[9:]}_name')
        self.short_name = (f'{self.table}.short_name', f'{self.table}.short_name as {self.table[9:]}_short_name')
        
                
class User(BaseTable):
    def __init__(self):
        super().__init__()
        self.email = (f'{self.table}.email', f'{self.table}.email as {self.table[9:]}_email')
        self.email_address_verified = (f'{self.table}.email_address_verified', f'{self.table}.email_address_verified as {self.table[9:]}_email_address_verified')
        self.email_verification_token = (f'{self.table}.email_verification_token', f'{self.table}.email_verification_token as {self.table[9:]}_email_verification_token')
        self.email_verification_expiry = (f'{self.table}.email_verification_expiry', f'{self.table}.email_verification_expiry as {self.table[9:]}_email_verification_expiry')
        self.title = (f'{self.table}.title', f'{self.table}.title as {self.table[9:]}_title')
        self.first_name = (f'{self.table}.first_name', f'{self.table}.first_name as {self.table[9:]}_first_name')
        self.last_name = (f'{self.table}.last_name', f'{self.table}.last_name as {self.table[9:]}_last_name')
        self.country_code = (f'{self.table}.country_code', f'{self.table}.country_code as {self.table[9:]}_country_code')
        self.auth0_id = (f'{self.table}.auth0_id', f'{self.table}.auth0_id as {self.table[9:]}_auth0_id')
        self.crm_id = (f'{self.table}.crm_id', f'{self.table}.crm_id as {self.table[9:]}_crm_id')
        self.status = (f'{self.table}.status', f'{self.table}.status as {self.table[9:]}_status')
        
                
class UserExternalAccount(BaseTable):
    def __init__(self):
        super().__init__()
        self.external_system_id = (f'{self.table}.external_system_id', f'{self.table}.external_system_id as {self.table[9:]}_external_system_id')
        self.user_id = (f'{self.table}.user_id', f'{self.table}.user_id as {self.table[9:]}_user_id')
        self.external_user_id = (f'{self.table}.external_user_id', f'{self.table}.external_user_id as {self.table[9:]}_external_user_id')
        self.status = (f'{self.table}.status', f'{self.table}.status as {self.table[9:]}_status')
        
                
class UserGroup(BaseTable):
    def __init__(self):
        super().__init__()
        self.name = (f'{self.table}.name', f'{self.table}.name as {self.table[9:]}_name')
        self.short_name = (f'{self.table}.short_name', f'{self.table}.short_name as {self.table[9:]}_short_name')
        self.url_code = (f'{self.table}.url_code', f'{self.table}.url_code as {self.table[9:]}_url_code')
        
                
class UserGroupMembership(BaseTable):
    def __init__(self):
        super().__init__()
        self.user_id = (f'{self.table}.user_id', f'{self.table}.user_id as {self.table[9:]}_user_id')
        self.user_group_id = (f'{self.table}.user_group_id', f'{self.table}.user_group_id as {self.table[9:]}_user_group_id')
        
                
class UserProject(BaseTable):
    def __init__(self):
        super().__init__()
        self.user_id = (f'{self.table}.user_id', f'{self.table}.user_id as {self.table[9:]}_user_id')
        self.project_id = (f'{self.table}.project_id', f'{self.table}.project_id as {self.table[9:]}_project_id')
        self.status = (f'{self.table}.status', f'{self.table}.status as {self.table[9:]}_status')
        self.ext_user_project_id = (f'{self.table}.ext_user_project_id', f'{self.table}.ext_user_project_id as {self.table[9:]}_ext_user_project_id')
        
                
class UserTask(BaseTable):
    def __init__(self):
        super().__init__()
        self.user_project_id = (f'{self.table}.user_project_id', f'{self.table}.user_project_id as {self.table[9:]}_user_project_id')
        self.project_task_id = (f'{self.table}.project_task_id', f'{self.table}.project_task_id as {self.table[9:]}_project_task_id')
        self.status = (f'{self.table}.status', f'{self.table}.status as {self.table[9:]}_status')
        self.consented = (f'{self.table}.consented', f'{self.table}.consented as {self.table[9:]}_consented')
        self.progress_info = (f'{self.table}.progress_info', f'{self.table}.progress_info as {self.table[9:]}_progress_info')
        self.ext_user_task_id = (f'{self.table}.ext_user_task_id', f'{self.table}.ext_user_task_id as {self.table[9:]}_ext_user_task_id')
        
                